### ISSUE TITLE
Update how productImage works in pyleapProjects.json

### ISSUE THREAD

**Issue by kattni** [adafruit/pyleap.github.io#2]
The README says this should be `URL to the primary image of a demo project in PNG format`, however at the moment, they are not full URLs. I discussed this with @TrevKnows and he said he wants to update how this works.

Filing an issue as this should be considered a priority as it's blocking my testing, and is definitely blocking moving forward to other testers.

**Comment by TrevKnows** [comment]
@kattni  Sure - the README has been updated, .JSON file has been updated and PyLeap gathers remote images in TestFlight version 1.1(4) of PyLeap.

**Comment by TrevKnows** [comment]
I was able to load the recently added project "Hand wash timer" to PyLeap after changing the NSURLRequest caching policy. In (TF) version 1.1(4) - users would need to remove the app, then download it again to see this project.
**The fix was already made and will be pushed out in (TF) version 1.1(5)** on Monday.

**Comment by kattni** [comment]
@TrevKnows Is the deleting and downloading the app again going to always be a requirement for seeing new projects in PyLeap? Or is fixing that what will be pushed out in 1.1(5)?

**Comment by TrevKnows** [comment]
@kattni deleting and downloading the app will not be required to see new projects in PyLeap. 
 The fix was pushed out in 1.1.(5)

**Comment by kattni** [comment]
Perfect. Thank you! Closing this issue.
